[WIP] Implement LSP
bytecodealliance/vscode-wit pull request #16
Opened 2023-06-11 11:28 UTC by cardoso

Closes #3 

Super WIP, but thought it might be good to have some initial feedback on the approach.

To test it out, have a recent version of wasm-tools installed, run `npm install`,  `npm start` & reload the vscode window.

## Preview

<img width="690" alt="Screenshot 2023-06-11 at 02 24 27" src="https://github.com/bytecodealliance/vscode-wit/assets/5606812/b5f5a97c-f7c5-4dfa-b150-018f34218655">

<img width="505" alt="Screenshot 2023-06-11 at 01 04 30" src="https://github.com/bytecodealliance/vscode-wit/assets/5606812/0c28a029-df2c-4375-bd8a-0744c6c3bd61">

2023-06-14 17:55 UTC, eduardomourar reviewed
@cardoso , thanks for your contribution! I will review this more throughly soon. I feel some tests are needed in this PR. Ideally we need both unit tests and some integration tests. Could you create some unit tests in the LSP rust code, please? After this is merged, I will work on the integration tests.

2023-06-14 21:08 UTC, cardoso commented
Thanks @eduardomourar - I'll get started on the tests

Some updates: Ultimately I decided to fork wit-parser so I could make some items public for more advanced features than linting such as semantic tokens, contextual hovering, etc.

This code would more appropriately live in the wasm-tools repository alongside wit-parser. 

My current thinking is for this to become a binary crate "wit-lsp" in wasm-tools with some of the logic pushed to the wit-parser crate under an "lsp" feature flag. 

This isn't blocking as I can keep using the fork for now, but I think moving to that approach would make the LSP more robust and easier to keep up-to-date. Also, keeping it separate from the VSCode extension would make it easier to port for other editors.

I can make that move if it makes sense.

2023-06-14 21:51 UTC, eduardomourar commented
@cardoso , let's keep the LSP code here for now in order to iterate more quickly (specially because I don't have permissions to the wasm-tools repository). To simplify that migration later on, we need to move all LSP related files to a folder called `./lsp`.

2023-06-14 22:01 UTC, eduardomourar commented on package.json
> +    "install": "npm run install:stable || npm run install:insiders",
After the move to the lsp folder:
```suggestion
    "build:lsp:debug": "cargo build --manifest-path=lsp/Cargo.toml",
    "build:lsp:release": "cargo build --manifest-path=lsp/Cargo.toml --release",
    "build:ext:debug": "esbuild ./extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node",
    "build:ext:release": "esbuild ./extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node --minify",
    "build:debug": "npm run build:lsp:debug && npm run build:ext:debug",
    "build:release": "npm run build:lsp:release && npm run build:ext:release",
    "build": "npm run build:debug",
    "package:lsp:debug": "cp ./lsp/target/debug/wit-lsp ./out/wit-lsp",
    "package:lsp:release": "cp ./lsp/target/release/wit-lsp ./out/wit-lsp",
    "package:ext:debug": "vsce package -o wit-idl.vsix",
    "package:ext:release": "vsce package -o wit-idl.vsix",
    "package:debug": "npm run package:lsp:debug && npm run package:ext:debug",
    "package:release": "npm run package:lsp:release && npm run package:ext:release",
    "package": "npm run package:debug",
    "install:plugin:insiders": "code-insiders --install-extension wit-idl.vsix",
    "install:plugin:stable": "code --install-extension wit-idl.vsix",
    "install:plugin": "npm run install:plugin:stable",
```

2023-06-14 22:05 UTC, eduardomourar commented on package.json
> +    "vscode-tmgrammar-test": "0.1.1"
Let's keep all of these with a caret (`^`) to allow security patches to go through. That is until we have dependabot enabled and fully automated release process.

2023-06-14 22:19 UTC, eduardomourar commented on .vscodeignore
> +.DS_Store
```suggestion
node_modules/**

commitlint.config.js

lsp/**
.DS_Store
```

2023-06-16 15:07 UTC, eduardomourar commented on .editorconfig
> +indent_size = 4
do we really need to change the indentation?

2023-06-16 15:08 UTC, eduardomourar commented on Cargo.toml
> +pulldown-cmark = "0.9"
the logger can be used add debug information specially in this exploratory phase
```suggestion
pulldown-cmark = "0.9"
log = "0.4"
env_logger = "0.10"
```

2023-06-16 15:10 UTC, eduardomourar commented on src/main.rs
> +}
```suggestion
#[macro_use]
extern crate log;

use tower_lsp::{LspService, Server};
use wit_lsp::WitLsp;

async fn start() {
    let stdin = tokio::io::stdin();
    let stdout = tokio::io::stdout();
    let (service, socket) = LspService::new(WitLsp::new);
    let server = Server::new(stdin, stdout, socket);
    server.serve(service).await;
}

#[tokio::main]
async fn main() {
    env_logger::init();

    debug!("starting language server up...");

    start().await;
}
```

2023-06-16 15:12 UTC, eduardomourar commented on extension.ts
> +}
Use an environment variable, for now, to change the log level.
```suggestion
import {window, workspace, type ExtensionContext} from 'vscode';
import {LanguageClient} from 'vscode-languageclient/node';

let client: LanguageClient;

export async function activate(context: ExtensionContext): Promise<void> {
	const traceOutputChannel = window.createOutputChannel('WIT Language Server trace');
	client = new LanguageClient(
		'witLanguageClient',
		'WIT Language Client',
		{
			command: context.asAbsolutePath('./out/wit-lsp'),
			options: {
				env: {
					...process.env,
					// eslint-disable-next-line @typescript-eslint/naming-convention
					RUST_LOG: 'debug',
				},
			},
		},
		{
			documentSelector: [{
				scheme: 'file',
				language: 'wit',
			}],
			synchronize: {
				fileEvents: workspace.createFileSystemWatcher('**/*.wit'),
			},
			traceOutputChannel,
		},
	);

	await client.start();
}
```

2023-06-16 15:22 UTC, eduardomourar requested changes

2023-06-16 15:22 UTC, eduardomourar commented on src/handler/capabilities.rs
> +        )),
by adding the semantic tokens provider here, the TextMate scopes are being overwritten. consequently, the highlighting is different before and after the LSP kicks in. while keeping the aesthetic as close as possible to the current setup, the scopes within `syntaxes/wit.tmLanguage.json` have to be modified to match [this expected mapping table](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#predefined-textmate-scope-mappings) or we have to define a custom mapping.

2025-05-13 16:59 UTC, closed without merging